#!/bin/bash
set -euo pipefail

# ============================================================
# Generate Pi-hole custom.list from .env
# Reads node IPs from .env and writes DNS records
# ============================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
ENV_FILE="${PROJECT_ROOT}/.env"
OUTPUT="${PROJECT_ROOT}/servers/gateway/pihole/custom.list"

if [[ ! -f "$ENV_FILE" ]]; then
    echo "ERROR: .env not found at ${ENV_FILE}"
    echo "Copy .env.template to .env and fill in your values first."
    exit 1
fi

# Source the .env file
set -a
source "$ENV_FILE"
set +a

# Validate required variables
for var in GATEWAY_IP AGENT_IP INFERENCE_IP NAS_IP; do
    if [[ -z "${!var:-}" ]]; then
        echo "ERROR: ${var} is not set in .env"
        exit 1
    fi
done

cat > "$OUTPUT" << EOF
# ============================================================
# Pi-hole Custom DNS Records
# Auto-generated by scripts/generate-pihole-dns.sh
# Do not edit manually — rerun the script after .env changes
# ============================================================

# ── Node hostnames ─────────────────────────────────────────
${GATEWAY_IP} gateway.home.local
${AGENT_IP} agent.home.local
${INFERENCE_IP} inference.home.local
${NAS_IP} nas.home.local
EOF

echo "Generated ${OUTPUT} with IPs from .env"
